name: Coverage Badge
on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  coverage:
    name: coverage badge
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.12"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests and generate coverage report
        run: |
          coverage run -m pytest
          coverage report

      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-py@v2.0.3
        with:
          output: coverage.svg

      - name: Commit coverage badge
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Checkout or create the branch
          git checkout -B coverage-badge

          # Stage and commit changes
          git add coverage.svg
          git commit -m "Add coverage badge" || echo "No changes to commit"

      - name: Force push
        run: |
          git push origin coverage-badge --force
